### ISSUE TITLE
mesh.write("mesh") always puts mesh at (0,0);

### ISSUE THREAD

**Issue by fgradi** [incardon/openfpm_pdata#2]
I create a 2D domain of size (size_x, size_y) _centered_ around (0,0):

```c++
    size_t res_x = 10, res_y = 15;               // mesh resolution in x and y
    double size_x = 2.,                         // physical domain size
           size_y = 3.,
           size_g = 0.25;

    domain_type domain({-size_x/2., -size_y/2.}, {size_x/2., size_y/2.});
    size_t szu[] = {res_x, res_y};
    mesh_type mesh(szu, domain, ghost, bc);

```

Writing the mesh to a file
```c++
    mesh.write("mesh"); // wrong
```
it shows up in paraview with its lower left corner _at_ (0,0), see attached screenshot.

The decomposition shows up fine though.
```c++  
    mesh.getDecomposition().write("mesh_decomp_"); // correct
```
I'll attach a .zip with the minimum example bug.cpp and a Makefile.

[mesh_write_bug.zip](https://github.com/incardon/openfpm_pdata/files/1654066/mesh_write_bug.zip)
![mesh_offset](https://user-images.githubusercontent.com/12770378/35251847-64713d68-0031-11e8-8183-154594ac1b43.png)

**Comment by incardon** [comment]
Thanks, for reporting. Confirmed, and reproducible

**Comment by incardon** [comment]
Fixed on the development version on the development repositories. Added test to avoid regressions derived patch for the released version attached to this message. Pushed changes to the release repo.

Thanks again for reporting, and sorry for the inconvenience

[0001-Fixing-getOffset.zip](https://github.com/incardon/openfpm_pdata/files/1656833/0001-Fixing-getOffset.zip)

**Comment by fgradi** [comment]
That was fast! Fixed it for me, too. Thanks heaps!
